# Generated by Django 4.2 on 2024-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbol_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
