# Generated by Django 4.2 on 2024-10-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbol_system', '0002_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
