# Generated by Django 4.2 on 2024-10-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symbol_system', '0003_driver_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='symbol_system.job'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='symbol_system.parcel'),
        ),
    ]
