# Generated by Django 4.2 on 2024-10-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbol_system', '0004_parcel_job_parcel_status_alter_job_parcel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='parcel',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
