# Generated by Django 4.2 on 2024-10-23 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symbol_system', '0005_remove_job_parcel_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_maintenance_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
