# Generated by Django 4.2 on 2024-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbol_system', '0006_vehicle_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], max_length=50),
        ),
    ]
